import { mkdtempSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { buildCliProgram } from "../core.js";

function interceptProcessExit() {
  return vi
    .spyOn(process, "exit")
    .mockImplementation(((code?: string | number | null) => {
      throw new Error(`process.exit:${code ?? 0}`);
    }) as typeof process.exit);
}

describe("mcp mobile CLI behavior", () => {
  const originalCwd = process.cwd();
  let tempDir = "";

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), "foundry-mobile-cli-"));
    process.chdir(tempDir);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    if (tempDir) {
      rmSync(tempDir, { recursive: true, force: true });
    }
    vi.restoreAllMocks();
  });

  it("allows mobile-only sync without a config file and reports the gateway-owned skip", async () => {
    const logSpy = vi.spyOn(console, "log").mockImplementation(() => {});
    const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});
    const exitSpy = interceptProcessExit();
    const program = buildCliProgram();

    await expect(
      program.parseAsync(
        ["mcp", "tools", "sync", "--service", "mobile", "--scope", "project"],
        { from: "user" },
      ),
    ).resolves.toBe(program);

    expect(exitSpy).not.toHaveBeenCalled();
    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining("mobile: skipped"),
    );
    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining("bundled MCP gateway runtime"),
    );
    expect(errorSpy).not.toHaveBeenCalled();
  });

  it("tells users to start the bundled gateway when no mobile catalog exists", async () => {
    const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});
    interceptProcessExit();
    const program = buildCliProgram();

    await expect(
      program.parseAsync(
        ["mcp", "tools", "list", "--service", "mobile", "--scope", "project"],
        { from: "user" },
      ),
    ).rejects.toThrow("process.exit:1");

    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining("Mobile catalogs are generated by the bundled MCP gateway."),
    );
    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining("cbx mcp serve --scope project"),
    );
  });

  it("keeps the missing-tool guidance explicit about sync versus bundled mobile discovery", async () => {
    const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});
    interceptProcessExit();
    const program = buildCliProgram();

    await expect(
      program.parseAsync(["mcp", "test", "tap", "--scope", "project"], {
        from: "user",
      }),
    ).rejects.toThrow("process.exit:1");

    expect(errorSpy).toHaveBeenCalledWith(
      expect.stringContaining(
        "Run 'cbx mcp tools sync --service all --scope project' for Postman/Stitch catalogs, or start the bundled MCP gateway to generate mobile catalogs.",
      ),
    );
  });
});
